title: Riley Horn # your name (or website title) here
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
logo: "images/Profile_Images/Riley_Portrait_Circle.PNG"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I'm a clinical researcher living in San Francisco. 
  My interests began with a fascination to better understand human movement and 
  it's application to movement disorders and sports performance. I am excited 
  about exploring new tools and technologies to contribute to meaningful 
  research in health science. I also enjoy running, writing, and making music with friends.
#  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: G-4TRZR1YCLX #your Google Analytics tracking ID here (e.g. UA-000000-0)

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

github:
  is_project_page: true
